name:                herp-prometheus
version:             0.1.0.0
#github:              "herp-inc/herp-hslib"
#license:             BSD3
#author:              "ruicc"
#maintainer:          "kousuke.ruichi@herp.co.jp"
#copyright:           "2021 HERP, Inc"

#extra-source-files:
#- README.md
#- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/herp-inc/herp-hslib#readme>

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5

  - text

  - wai

  - prometheus-client
  - prometheus-metrics-ghc
  - wai-middleware-prometheus

#executables:
#  herp-hslib-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - herp-hslib
#
#tests:
#  herp-hslib-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - herp-hslib
